---
# Launch the vacuum every work day at the selected hour
#
# Exception if the house is put in mode holidays with the thru an
# input_select
#
- alias: Lancemnent quotidien de Rocky
  initial_state: true
  trigger:
    # platform: time
    # at: '10:00:00'
    platform: template
    value_template: "{{ states('sensor.time') == state_attr('input_datetime.vacuum_start_hour', 'timestamp') | timestamp_custom('%H:%M', False) }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Normal'
  action:
    service: script.turn_on
    entity_id: script.vacuum_workday_sequence
