---
# Pool pump duration during swiming season
#
# Inpired by exxamalte implementation: https://github.com/exxamalte/home-assistant-customisations/tree/master/pool-pump
#
run_pool_pump_hours_swimming_season:
  name: Run Pool Pump in Swimming Season
  min: 1
  max: 8
  step: 1
