---
# Pool pump duration during off season
#
# Inpired by exxamalte implementation: https://github.com/exxamalte/home-assistant-customisations/tree/master/pool-pump
#
run_pool_pump_hours_off_season:
  name: Run Pool Pump in Off Season
  min: 1
  max: 6
  step: 1
