---
# Follow the mileage of the last maintenance of the Qashqai
#
qashqai_last_maintenance_km:
  name: Kilométrage de la dernière révision du Qashqai
  icon: mdi:counter
  mode: box
  min: 0
  max: 300000
  unit_of_measurement: km
