resources:
  - type: js
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: js
    url: /local/linky-card.js?v=4
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - type: js
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: js
    url: /customcards/weasley-card.js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: js
title: Maison
views:
  - badges:
      - sun.sun
      - sensor.aurade_next_rain
      - sensor.aurade_weather_alert
      - binary_sensor.meteoalarm
    cards:
      - entity: weather.dark_sky
        name: Météo DarkSky
        type: weather-forecast
      - entities:
          - entity: sensor.exterieur_temperature
          - entity: sensor.exterieur_humidity
        title: Extérieur
        type: glance
      - entity: weather.aurade
        type: weather-forecast
      - entities:
          - entity: sensor.temperature_salon
          - entity: sensor.temperature_parents
          - entity: sensor.temperature_noah
          - entity: sensor.temperature_athenais
          - entity: sensor.temperature_soren
          - entity: sensor.temperature_cave
        show_header_toggle: false
        title: Températures
        type: entities
    icon: 'mdi:home'
    path: default_view
    title: Maison
  - badges: []
    cards:
      - entities:
          - entity: vacuum.rocky
          - entity: sensor.vacuum_cleaner_error_sensor
          - entity: sensor.vacuum_cleaner_status_sensor
        show_header_toggle: false
        title: Rocky
        type: entities
      - entities:
          - entity: input_boolean.vacuum_can_clean_the_kitchen
          - entity: input_boolean.vacuum_can_clean_the_entrance
          - entity: input_boolean.vacuum_can_clean_the_living_room_safe
          - entity: input_boolean.vacuum_can_clean_the_living_room
          - entity: input_boolean.vacuum_can_clean_the_coridor
          - entity: input_boolean.vacuum_can_clean_the_office
          - entity: input_boolean.vacuum_can_clean_athenais_bedroom
          - entity: input_boolean.vacuum_can_clean_noah_bedroom
          - entity: input_boolean.vacuum_can_clean_soren_bedroom
          - entity: input_boolean.vacuum_can_clean_the_carpet
          - entity: input_boolean.vacuum_can_clean_kids_bathroom
          - entity: input_boolean.vacuum_can_clean_parental_suite
        title: Pièces à nettoyer aujourd'hui
        type: entities
      - entities:
          - entity: input_boolean.vacuum_need_to_be_emptied
        type: entities
      - entities:
          - entity: script.vacuum_workday_sequence
          - entity: script.vacuum_map_construct
        title: Scripts de la routine
        type: entities
    icon: 'mdi:robot-vacuum'
    title: Rocky
  - badges: []
    cards:
      - entity: alarm_control_panel.ha_alarm
        name: Alarme
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - entities:
          - entity: input_select.house_mode
        type: glance
      - entities:
          - entity: binary_sensor.main_door
          - entity: binary_sensor.garage_door
        type: glance
      - entities:
          - entity: binary_sensor.water_leak_sensor_buanderie
        show_header_toggle: false
        title: Détection fuite d'eau
        type: entities
      - entities:
          - entity: binary_sensor.motion_house_meta
          - entity: variable.last_motion
          - entity: binary_sensor.motion_sensor_livingroom
        show_header_toggle: false
        title: Détecteurs de mouvement
        type: entities
    icon: 'mdi:shield-home'
    panel: false
    title: Sécurité
  - badges: []
    cards:
      - entities:
          - entity: switch.prise_pc_switch
          - entity: switch.prise_tv_switch
        show_state: false
        title: Prises commandées
        type: glance
      - entity: sensor.prise_pc_power
        max: 300
        min: 0
        name: Conso PC
        severity:
          green: 0
          red: 200
          yellow: 7
        theme: default
        type: gauge
      - entity: sensor.prise_tv_power
        max: 150
        min: 0
        name: Conso TV
        severity:
          green: 0
          red: 100
          yellow: 25
        theme: default
        type: gauge
      - entity: sensor.linky
        type: 'custom:linky-card'
    icon: 'mdi:power-plug'
    title: Énerige
  - badges:
      - binary_sensor.temp_falling
      - binary_sensor.temp_rising
    cards:
      - card:
          title: Lights on
          type: glance
        filter:
          exclude:
            - entity_id: light.home_hassistant
          include:
            - domain: light
              options:
                tap_action:
                  action: toggle
              state: 'on'
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.trajet_maison_travail_benoit
          - entity: sensor.trajet_maison_travail_alex
        title: Trajets
        type: glance
      - entities:
          - card:
              head:
                label: Désactivées
                type: section
              type: 'custom:fold-entity-row'
            filter:
              include:
                - domain: automation
                  state: 'off'
            show_empty: false
            type: 'custom:auto-entities'
          - card:
              head:
                label: Activées
                type: section
              type: 'custom:fold-entity-row'
            filter:
              include:
                - domain: automation
                  state: 'on'
            show_empty: false
            type: 'custom:auto-entities'
        title: Automatismes
        type: entities
      - entities:
          - head: group.all_scripts
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: Scripts
        type: entities
      - card:
          title: Tracker Home
          type: glance
        filter:
          include:
            - domain: device_tracker
              state: home
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.illumination_158d0001e575b0
          - entity: sensor.humidity_cave
        type: entities
    icon: 'mdi:robot'
    title: Automatismes
  - badges:
      - sensor.plex
    cards:
      - entity: media_player.tele
        type: media-control
      - entity: media_player.google_home
        type: media-control
      - entity: media_player.samsung_led48_ue48h6200
        type: media-control
    icon: 'mdi:theater'
    title: Média
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.xiaomi_gateway
          - entity: binary_sensor.rocky
          - entity: binary_sensor.hue_gateway
          - entity: binary_sensor.nas
          - entity: binary_sensor.google_home
        title: Systèmes
        type: glance
      - entities:
          - entity: binary_sensor.blizzard
          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
        title: Internet
        type: glance
      - card:
          show_header_toggle: false
          title: Batteries faibles
          type: entities
        filter:
          exclude:
            - domain: vacuum
            - entity_id: '*pressure*'
            - entity_id: '*humidity*'
            - entity_id: sensor.presence_couloir_temperature
            - entity_id: sensor.presence_couloir_light_level
          include:
            - attributes:
                battery_level: <= 30
              options:
                secondary_info: 'Battery_level: [[ {entity}.attributes.battery_level ]]'
                type: 'custom:secondaryinfo-entity-row'
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.processor_use
          - entity: sensor.disk_use_percent
          - entity: sensor.memory_use_percent
          - entity: sensor.cpu_temperature
          - entity: sensor.last_boot
        show_header_toggle: false
        title: Raspberry
        type: entities
      - entities:
          - zwave.aeotec_zw090_zstick_gen5_eu
          - zwave.detecteur_de_fumee
          - zwave.prise_tv
          - zwave.prise_pc
        title: Z-Wave
        type: entities
      - card:
          show_header_toggle: false
          title: Entites indisponibles
          type: entities
        filter:
          exclude:
            - domain: vacuum
            - entity_id: '*pressure*'
            - entity_id: '*humidity*'
            - entity_id: sensor.presence_couloir_temperature
            - entity_id: sensor.presence_couloir_light_level
            - entity_id: group.all_vacuum_cleaners
          include:
            - state: unknown
        show_empty: true
        type: 'custom:auto-entities'
    icon: 'mdi:lan'
    title: Réseau
  - badges: []
    cards:
      - fontname: itcblkad_font
        locations:
          - Maison
          - Travail
          - Collège
          - École
        lost: Perdu
        travelling: En voyage
        type: 'custom:weasley-card'
        wizards:
          - entity: person.benoit
            name: Benoit
          - entity: device_tracker.hermiones_phone
            name: Alex
          - entity: calendar.ron
            name: Noah
          - entity: calendat.noah
            name: Athénaïs
          - entity: calendar.ginny
            name: Sören
      - aspect_ratio: '16:9'
        entities:
          - entity: zone.home
          - entity: zone.travail_alex
          - entity: zone.travail_benoit
          - entity: zone.college
          - entity: zone.ecole
        type: map
    icon: 'mdi:map-marker'
    panel: false
    title: Map
  - badges:
      - sensor.exterieur_temperature
    cards:
      - entity: sensor.aurade_uv
        max: 10
        min: 0
        name: Indice UV
        severity:
          green: 1
          red: 6
          yellow: 3
        theme: default
        type: gauge
    icon: 'mdi:pool'
    title: Piscine

