---
# Request receive by Telegram to let light on
#
# This automation is linked to:
# - request_check_again_in_15_min.yaml
# - request_keep_lights.yaml
# - request_switch_off_lights.yaml
# - check_lights_vs_sunrise.yaml
#
alias: Ne pas éteindre les lumières
initial_state: true
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /do_nothing
action:
- service: telegram_bot.answer_callback_query
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    message: Tu as dis non!
- service: telegram_bot.edit_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
    message: 'OK je laisse les lumières allumées'