alias: Redemande dans 15 minutes
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /redemande
action:
- service: timer.start
  entity_id: timer.redemande_leve_du_soleil
- service: telegram_bot.edit_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
    message: 'OK je te redemande dans 15 minutes'