alias: Ne pas éteindre les lumières
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /do_nothing
action:
- service: telegram_bot.answer_callback_query
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    message: Tu as dis non!
- service: telegram_bot.edit_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
    message: 'OK je laisse les lumières allumées'