---
# Notifications to monitor internal devices.
# One when detected down. Another when back online.
# 
- alias: 'Notification de système KO'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.google_home
      to: 'off'
    - platform: state
      entity_id: binary_sensor.NAS
      to: 'off'
    - platform: state
      entity_id: binary_sensor.hue_gateway
      to: 'off'
    - platform: state
      entity_id: binary_sensor.rocky
      to: 'off'
    - platform: state
      entity_id: binary_sensor.xiaomi_gateway
      to: 'off'
  action:
    - service: notify.telegram
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} ne répond plus.
    - service: persistent_notification.create
      data_template:
        title: Un système est KO
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} ne répond plus.
        notification_id: system_KO

- alias: "Notification système back online"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.google_home
      to: 'on'
    - platform: state
      entity_id: binary_sensor.NAS
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hue_gateway
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rocky
      to: 'on'
    - platform: state
      entity_id: binary_sensor.xiaomi_gateway
      to: 'on'
  action:
    - service: notify.telegram
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is back online !.
