---
# Used for statistic report of the latest daily routine
#
# https://github.com/rogro82/hass-variables
#
name: "Avant routine Rocky"
value: "unknown"
restore: true
attributes:
  time: "unknown"
  area: "unknown"
