---
# Used for motion detection
#
# https://github.com/rogro82/hass-variables
#
name: "Status lors du dernier vidage du bac"
value: "unknown"
restore: true
attributes:
  time: "unknown"
  area: "unknown"
