##
## Discussion pour éteindre les lumières après le levé du soleil
##

- alias: Eteindre éclairage au levé du soleil
  initial_state: true
  hide_entity: false
  trigger:
  - event: sunrise
    offset: 0:15:00
    platform: sun
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.redemande_leve_du_soleil
  action:
  - data:
      data:
        inline_keyboard:
        - Oui:/eteintLumiere, Non:/do_nothing, Redemande:/redemande
      message: Le soleil est levé et il reste des lumières allumées dans le salon.
        Voulez vous les éteindre ?
    service: notify.telegram
  condition:
  - condition: state
    entity_id: light.salon
    state: 'on'

- alias: Ne pas éteindre les lumières
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /do_nothing
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: OK, you said no!
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      message: 'OK je laisse les lumières allumées'

- alias: Éteindre les lumières
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /eteintLumiere
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: J'éteins les lumières
  - service: light.turn_off
    entity_id: light.salon
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      message: 'Les lumières du salon sont éteintes'

- alias: Redemande dans 15 minutes
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /redemande
  action:
  - service: timer.start
    entity_id: timer.redemande_leve_du_soleil
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      message: 'OK je te redemande dans 15 minutes'

##
## Notification on reboot de Home assistant
##

- alias: notification au reboot de Home Assistant
  condition: []
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: notify.telegram
    data:
      message: "Home Assitant a redémarré !"
