---
# Notify the max UV index every day after first update of the sensor value
#
- alias: Notify the max UV index daily
  trigger:
    platform: state
    entity_id: sensor.max_uv_index
  action:
    - service: notify.telegram
      data_template:
        message: "Index UV max de la journée: {{states('sensor.max_uv_index') | round}}"
