---
# Launch my Xiamoi vacuum with my Google assistant thru IFTTT
#
# Integration in Telegram inspired by https://medium.com/@honcheng/how-i-got-my-vacuum-cleaner-to-talk-back-to-me-via-telegram-d4b471b7598c
#
id: launch_vacuum_in_selected_room
# Launch vacuum with Google Home through IFTTT. User can select the room name
alias: lance Rocky
trigger: 
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_rocky
action: 
  service: script.turn_on
  data_template:
    entity_id: >
      {% if (trigger.event.data.room== "la partie jour") or "dans la partie jour" %}
        script.launch_vacuum_in_kitchen_and_livingroom
      {% endif %}