---
# Send a notification if alarm is triggered
#
alias: 'Send notification when alarm triggered'
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'triggered'
action:
  - service: notify.telegram
    data:
      message: "ALARM! L'alarme a été déclanchée."
