---
# Send a notification on Telegram if the previous error of the vacuum
# is solved.
#
# Integration in Telegram inspired by https://medium.com/@honcheng/how-i-got-my-vacuum-cleaner-to-talk-back-to-me-via-telegram-d4b471b7598c
#
id: vacuum_cleaner_error_solved
# Notification to inform when problem solved
alias: Vacuum Cleaner Error Solved
trigger:
  - platform: state
    entity_id: sensor.vacuum_cleaner_error_sensor
    to: 'No Error'
action:
  - service: notify.telegram
    data:
      title: '*Rocky*'
      message: Plus d'erreur. Problème résolu