esphome:
  name: capteur_piscine
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Example configuration entry
dallas:
  - id: dallas_hub1
    pin: 4
    update_interval: 1s

# Individual sensors
sensor:
  - platform: dallas
    dallas_id: "dallas_hub1"
    address: 0x9C0417C1A988FF28
    name: "Température Piscine"
    icon: "mdi:oil-temperature"

deep_sleep:
  run_duration: 20s
  sleep_duration: 1h
  #TODO: prevent deep sleep

#TODO: signal wifi