---
# Sensor to monitor the power consumtion of the pool pump
#
# Inpired by AlexxIT implementation: https://github.com/exxamalte/home-assistant-customisations/tree/master/pool-pump
#
platform: template
sensors:
  pool_pump_power:
    value_template: "{{ state_attr('switch.sonoff_pow_piscine', 'power') }}"
    friendly_name: "Pool Pump power"
    device_class: power
    unit_of_measurement: "W"
