vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.36
    token: !secret vacuum_xiaomi_token

#Vacuum integration in Telegram inspired by https://medium.com/@honcheng/how-i-got-my-vacuum-cleaner-to-talk-back-to-me-via-telegram-d4b471b7598c
sensor:
  - platform: template
    #sensor to catch the error of the Roborock if any
    sensors:
      vacuum_cleaner_error_sensor:
        friendly_name: Vacuum Cleaner Error Sensor
        value_template: >-
          {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
            {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
          {% else %}
            No Error
          {% endif %}


automation:
  - id: vacuum_cleaner_error
    # Notification if any error message raised by Roborock
    alias: Vacuum Cleaner Error
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'In Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Charging Error'
    action:
      - service: notify.telegram
        data:
          title: '*Problème avec Rocky*'
          message: >-
            {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error')  %}
              {{states.sensor.vacuum_cleaner_status_sensor.state}}
            {% else %}
              {{states.sensor.vacuum_cleaner_error_sensor.state}}
            {% endif %}
  - id: vacuum_cleaner_error_solved
    # Notification to inform when problem solved
    alias: Vacuum Cleaner Error Solved
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_error_sensor
        to: 'No Error'
    action:
      - service: notify.telegram
        data:
          title: '*Rocky*'
          message: Plus d'erreur. Problème résolu
  - id: launch_vacuum_in_selected_room
    # Launch vacuum with Google Home through IFTTT. User can select the room name
    alias: lance Rocky
    trigger: 
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_rocky
    action: 
      service: script.turn_on
      data_template:
        entity_id: >
          {% if (trigger.event.data.room== "la partie jour") or "dans la partie jour" %}
            script.launch_vacuum_in_kitchen_and_livingroom
          {% endif %}
          
  - id: stop_vacuum
    # Stop vacuum with Google Home through IFTTT. And go back to dock
    alias: stop Rocky
    trigger: 
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: stop_rocky
    action: 
      service: notify.telegram
      data:
        message: >
          OK je stop Rocky. Il retourne sa base. 

# Coordonnées pratique:
# dock: [25000,25000]
# buanderie(bl): [20600,21000]
# sallon(tr): [30500, 29300]
# cuisine(bl): []
# cuisine(tr): [27000,25000]
# maison(bl): []
# maison(tr): []
# tapis(bl): []
# tapis(tr): []
# salleamanger(tr): []

script:
  launch_vacuum_in_kitchen_and_livingroom:
    # used with ifttt with POST command https://my_url.com/api/services/script/launch_vacuum_in_kitchen_and_livingroom?api_password=API_PASSWORD
    alias: Lance Rocky dans la cuisine et le salon
    sequence: 
      - service: vacuum.set_fan_speed
        data: 
          entity_id: vacuum.xiaomi_vacuum_cleaner
          fan_speed: balanced
      - service: vacuum.send_command
        data: 
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [[20600,21000,30500,29300,1]]


          