vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.36
    token: !secret vacuum_xiaomi_toket

#Vacuum integration in Telegram inspired by https://medium.com/@honcheng/how-i-got-my-vacuum-cleaner-to-talk-back-to-me-via-telegram-d4b471b7598c
sensor:
  - platform: template
    #sensor to catch the error of the Roborock if any
    sensors:
      vacuum_cleaner_error_sensor:
        friendly_name: Vacuum Cleaner Error Sensor
        value_template: >-
          {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
            {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
          {% else %}
            No Error
          {% endif %}


automation:
  - id: vacuum_cleaner_error
    # Notification if any error message raised by Roborock
    alias: Vacuum Cleaner Error
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'In Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Charging Error'
    action:
      - service: notify.telegram
        data:
          title: '*Problème avec Rocky*'
          message: >-
            {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error')  %}
              {{states.sensor.vacuum_cleaner_status_sensor.state}}
            {% else %}
              {{states.sensor.vacuum_cleaner_error_sensor.state}}
            {% endif %}
  - id: vacuum_cleaner_error_solved
    # Notification to inform when problem solved
    alias: Vacuum Cleaner Error Solved
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_error_sensor
        to: 'No Error'
    action:
      - service: notify.telegram
        data:
          title: '*Rocky*'
          message: Plus d'erreur. Problème résolu

  - id: vacuum_cleaner_status_changed
    alias: Vacuum Cleaner Status cCanged
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
    action:
      - service: notify.telegram
        data:
          title: '*Rocky*'
          message: >-
            {{states.vacuum.xiaomi_vacuum_cleaner.state}}
          