---
# Google map integration
#
# To follow kids position as they are in Google Family link
#
# https://www.home-assistant.io/integrations/google_maps/
#
platform: google_maps
username: !secret google_maps_email
